# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Don't Panic
tagline:          'Thoughts, stories and ideas'
description:      'Thoughts, stories and ideas'
url:              
baseurl:          /

author:
  name:           'Junaid K'
  url:            https://twitter.com/Junaid_kld

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/junaidk
